http:
  host: 0.0.0.0
  port: 8080
postgresql:
  user:
  password:
  host:
  port:
  database: hotels_system
  ssl_mode:
jwt:
  sign_key:
  token_ttl: 60m
postgres:
  user: postgres
  password: 5432
  host: localhost
  port: 5432
  database: hotels_system
  ssl_mode: disable
redis:
  host: localhost
  port: 6379
  password: 1234
  db: 0