services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
      POSTGRES_DB: "hotels_system"
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1234
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    volumes:
      - app_redis_data:/data
    healthcheck:
      test: sh -c "redis-cli -a $$REDIS_PASSWORD ping"
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  service:
    build:
      context: .
    restart: always
    environment:
      APP_ENV: prod
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8080
      PG_USER: postgres
      PG_PASSWORD: 5432
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: hotels_system
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 1234
      REDIS_DB: 0
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  app_pg_data:
  app_redis_data: 