// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Логин",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "аутентификация"
                ],
                "summary": "Логин",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_request.Login"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_response.Login"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Регенерация токена",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "аутентификация"
                ],
                "summary": "Регенерация токена",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_request.Refresh"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_response.Refresh"
                        }
                    }
                }
            }
        },
        "/v1/hotel/rooms": {
            "post": {
                "description": "Получение доступных типов комнат",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "отель"
                ],
                "summary": "Получение доступных типов комнат",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_request.GetRooms"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_response.GetAllRooms"
                        }
                    }
                }
            }
        },
        "/v1/hotel/rooms/reserve": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Бронь комнаты",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "отель"
                ],
                "summary": "Бронь",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_request.ReserveRoom"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/hotel/rooms/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение информации по комнате для админки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "отель"
                ],
                "summary": "Получение информации по комнате для админки",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор комнаты",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_usamaroman_demo_indev_hackathon_backend_internal_entity.Room"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_request.GetRooms": {
            "type": "object",
            "required": [
                "end_date",
                "start_date"
            ],
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "29.05.2026"
                },
                "start_date": {
                    "type": "string",
                    "example": "01.12.2025"
                }
            }
        },
        "github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_request.Login": {
            "type": "object",
            "required": [
                "login"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "example": "admin"
                },
                "password": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 4,
                    "example": "admin"
                }
            }
        },
        "github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_request.Refresh": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "refresh_token"
                }
            }
        },
        "github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_request.ReserveRoom": {
            "type": "object",
            "required": [
                "end_date",
                "room_type",
                "start_date"
            ],
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "29.05.2026"
                },
                "room_type": {
                    "type": "integer",
                    "example": 1
                },
                "start_date": {
                    "type": "string",
                    "example": "01.12.2025"
                }
            }
        },
        "github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_response.GetAllRooms": {
            "type": "object",
            "properties": {
                "rooms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_usamaroman_demo_indev_hackathon_backend_internal_entity.RoomType"
                    }
                }
            }
        },
        "github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_response.Login": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "access_token"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "refresh_token"
                },
                "user": {
                    "$ref": "#/definitions/github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_response.User"
                }
            }
        },
        "github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_response.Refresh": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "access_token"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "refresh_token"
                }
            }
        },
        "github_com_usamaroman_demo_indev_hackathon_backend_internal_controller_v1_response.User": {
            "type": "object",
            "properties": {
                "business_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string"
                }
            }
        },
        "github_com_usamaroman_demo_indev_hackathon_backend_internal_entity.Room": {
            "type": "object",
            "properties": {
                "floor": {
                    "type": "integer"
                },
                "hotel_id": {
                    "type": "integer"
                },
                "room_number": {
                    "type": "string"
                },
                "room_type_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_usamaroman_demo_indev_hackathon_backend_internal_entity.RoomType": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "CRM Backend API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
