definitions:
  entity.Room:
    properties:
      floor:
        type: integer
      hotel_id:
        type: integer
      room_number:
        type: string
      room_type_id:
        type: integer
    type: object
  entity.RoomType:
    properties:
      capacity:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
  request.GetRooms:
    properties:
      end_date:
        example: 29.05.2026
        type: string
      start_date:
        example: 01.12.2025
        type: string
    required:
    - end_date
    - start_date
    type: object
  request.Light:
    properties:
      state:
        example: "true"
        type: string
    required:
    - state
    type: object
  request.Login:
    properties:
      login:
        example: admin
        type: string
      password:
        example: admin
        maxLength: 50
        minLength: 4
        type: string
    required:
    - login
    type: object
  request.Refresh:
    properties:
      refresh_token:
        example: refresh_token
        type: string
    required:
    - refresh_token
    type: object
  request.ReserveRoom:
    properties:
      end_date:
        example: 29.05.2026
        type: string
      room_type:
        example: 1
        type: integer
      start_date:
        example: 01.12.2025
        type: string
    required:
    - end_date
    - room_type
    - start_date
    type: object
  request.UpdateReservationStatus:
    properties:
      status:
        description: confirmed, checked_in, checked_out
        example: confirmed
        type: string
    required:
    - status
    type: object
  response.GetAllRooms:
    properties:
      rooms:
        items:
          $ref: '#/definitions/entity.RoomType'
        type: array
    type: object
  response.Login:
    properties:
      access_token:
        example: access_token
        type: string
      refresh_token:
        example: refresh_token
        type: string
      user:
        $ref: '#/definitions/response.User'
    type: object
  response.Refresh:
    properties:
      access_token:
        example: access_token
        type: string
      refresh_token:
        example: refresh_token
        type: string
    type: object
  response.RoomInfo:
    properties:
      is_active:
        type: boolean
      room:
        $ref: '#/definitions/entity.Room'
    type: object
  response.Token:
    properties:
      token:
        type: string
    type: object
  response.User:
    properties:
      business_id:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      login:
        type: string
      user_type:
        type: string
    type: object
info:
  contact: {}
  title: CRM Backend API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Логин
      parameters:
      - description: Тело запроса
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Login'
      summary: Логин
      tags:
      - аутентификация
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Регенерация токена
      parameters:
      - description: Тело запроса
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.Refresh'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Refresh'
      summary: Регенерация токена
      tags:
      - аутентификация
  /v1/hotel/rooms:
    post:
      consumes:
      - application/json
      description: Получение доступных типов комнат
      parameters:
      - description: Тело запроса
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.GetRooms'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetAllRooms'
      summary: Получение доступных типов комнат
      tags:
      - отель
  /v1/hotel/rooms/{id}:
    get:
      description: Получение информации по комнате для админки
      parameters:
      - description: Идентификатор комнаты
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RoomInfo'
      security:
      - BearerAuth: []
      summary: Получение информации по комнате для админки
      tags:
      - отель
  /v1/hotel/rooms/dump_token:
    get:
      description: Получение токена комнаты [ХАРДКОД]
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Token'
      summary: Получение токена комнаты [ХАРДКОД]
      tags:
      - отель
  /v1/hotel/rooms/light:
    post:
      consumes:
      - application/json
      description: Тогл света в комнате
      parameters:
      - description: Тело запроса
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.Light'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: Свет
      tags:
      - отель
  /v1/hotel/rooms/reservations/{id}:
    patch:
      consumes:
      - application/json
      description: Обновление статуса брони
      parameters:
      - description: ID брони
        in: path
        name: id
        required: true
        type: string
      - description: Тело запроса
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.UpdateReservationStatus'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: Обновление статуса брони
      tags:
      - отель
  /v1/hotel/rooms/reserve:
    post:
      consumes:
      - application/json
      description: Бронь комнаты
      parameters:
      - description: Тело запроса
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.ReserveRoom'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: Бронь
      tags:
      - отель
  /v1/hotel/rooms/token:
    get:
      consumes:
      - application/json
      description: Получение токена комнаты
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Token'
      security:
      - BearerAuth: []
      summary: Получение токена комнаты
      tags:
      - отель
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
