// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: proto/proto.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Statuses int32

const (
	Statuses_Ok    Statuses = 0
	Statuses_Error Statuses = 1
)

// Enum value maps for Statuses.
var (
	Statuses_name = map[int32]string{
		0: "Ok",
		1: "Error",
	}
	Statuses_value = map[string]int32{
		"Ok":    0,
		"Error": 1,
	}
)

func (x Statuses) Enum() *Statuses {
	p := new(Statuses)
	*p = x
	return p
}

func (x Statuses) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Statuses) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_proto_enumTypes[0].Descriptor()
}

func (Statuses) Type() protoreflect.EnumType {
	return &file_proto_proto_proto_enumTypes[0]
}

func (x Statuses) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Statuses.Descriptor instead.
func (Statuses) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0}
}

type LighStates int32

const (
	LighStates_On  LighStates = 0
	LighStates_Off LighStates = 1
)

// Enum value maps for LighStates.
var (
	LighStates_name = map[int32]string{
		0: "On",
		1: "Off",
	}
	LighStates_value = map[string]int32{
		"On":  0,
		"Off": 1,
	}
)

func (x LighStates) Enum() *LighStates {
	p := new(LighStates)
	*p = x
	return p
}

func (x LighStates) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LighStates) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_proto_enumTypes[1].Descriptor()
}

func (LighStates) Type() protoreflect.EnumType {
	return &file_proto_proto_proto_enumTypes[1]
}

func (x LighStates) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LighStates.Descriptor instead.
func (LighStates) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{1}
}

type DoorLockStates int32

const (
	DoorLockStates_Open  DoorLockStates = 0
	DoorLockStates_Close DoorLockStates = 1
)

// Enum value maps for DoorLockStates.
var (
	DoorLockStates_name = map[int32]string{
		0: "Open",
		1: "Close",
	}
	DoorLockStates_value = map[string]int32{
		"Open":  0,
		"Close": 1,
	}
)

func (x DoorLockStates) Enum() *DoorLockStates {
	p := new(DoorLockStates)
	*p = x
	return p
}

func (x DoorLockStates) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DoorLockStates) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_proto_enumTypes[2].Descriptor()
}

func (DoorLockStates) Type() protoreflect.EnumType {
	return &file_proto_proto_proto_enumTypes[2]
}

func (x DoorLockStates) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DoorLockStates.Descriptor instead.
func (DoorLockStates) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{2}
}

type ChannelStates int32

const (
	ChannelStates_ChannelOn  ChannelStates = 0
	ChannelStates_ChannelOff ChannelStates = 1
)

// Enum value maps for ChannelStates.
var (
	ChannelStates_name = map[int32]string{
		0: "ChannelOn",
		1: "ChannelOff",
	}
	ChannelStates_value = map[string]int32{
		"ChannelOn":  0,
		"ChannelOff": 1,
	}
)

func (x ChannelStates) Enum() *ChannelStates {
	p := new(ChannelStates)
	*p = x
	return p
}

func (x ChannelStates) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelStates) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_proto_enumTypes[3].Descriptor()
}

func (ChannelStates) Type() protoreflect.EnumType {
	return &file_proto_proto_proto_enumTypes[3]
}

func (x ChannelStates) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelStates.Descriptor instead.
func (ChannelStates) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{3}
}

type States int32

const (
	States_LightOn       States = 0
	States_LightOff      States = 1
	States_DoorLockOpen  States = 2
	States_DoorLockClose States = 3
	States_Channel1On    States = 4
	States_Channel1Off   States = 5
	States_Channel2On    States = 6
	States_Channel2Off   States = 7
)

// Enum value maps for States.
var (
	States_name = map[int32]string{
		0: "LightOn",
		1: "LightOff",
		2: "DoorLockOpen",
		3: "DoorLockClose",
		4: "Channel1On",
		5: "Channel1Off",
		6: "Channel2On",
		7: "Channel2Off",
	}
	States_value = map[string]int32{
		"LightOn":       0,
		"LightOff":      1,
		"DoorLockOpen":  2,
		"DoorLockClose": 3,
		"Channel1On":    4,
		"Channel1Off":   5,
		"Channel2On":    6,
		"Channel2Off":   7,
	}
)

func (x States) Enum() *States {
	p := new(States)
	*p = x
	return p
}

func (x States) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (States) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_proto_enumTypes[4].Descriptor()
}

func (States) Type() protoreflect.EnumType {
	return &file_proto_proto_proto_enumTypes[4]
}

func (x States) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use States.Descriptor instead.
func (States) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{4}
}

type IdentifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *IdentifyRequest) Reset() {
	*x = IdentifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyRequest) ProtoMessage() {}

func (x *IdentifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyRequest.ProtoReflect.Descriptor instead.
func (*IdentifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0}
}

func (x *IdentifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetState) Reset() {
	*x = GetState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetState) ProtoMessage() {}

func (x *GetState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetState.ProtoReflect.Descriptor instead.
func (*GetState) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{1}
}

type GetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetInfo) Reset() {
	*x = GetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfo) ProtoMessage() {}

func (x *GetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfo.ProtoReflect.Descriptor instead.
func (*GetInfo) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{2}
}

type SetState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State States `protobuf:"varint,1,opt,name=state,proto3,enum=api.States" json:"state,omitempty"`
}

func (x *SetState) Reset() {
	*x = SetState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetState) ProtoMessage() {}

func (x *SetState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetState.ProtoReflect.Descriptor instead.
func (*SetState) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{3}
}

func (x *SetState) GetState() States {
	if x != nil {
		return x.State
	}
	return States_LightOn
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LightOn     LighStates     `protobuf:"varint,1,opt,name=light_on,json=lightOn,proto3,enum=api.LighStates" json:"light_on,omitempty"`
	DoorLock    DoorLockStates `protobuf:"varint,2,opt,name=door_lock,json=doorLock,proto3,enum=api.DoorLockStates" json:"door_lock,omitempty"`
	Channel_1   ChannelStates  `protobuf:"varint,3,opt,name=channel_1,json=channel1,proto3,enum=api.ChannelStates" json:"channel_1,omitempty"`
	Channel_2   ChannelStates  `protobuf:"varint,4,opt,name=channel_2,json=channel2,proto3,enum=api.ChannelStates" json:"channel_2,omitempty"`
	Temperature float32        `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Pressure    float32        `protobuf:"fixed32,6,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Humidity    float32        `protobuf:"fixed32,7,opt,name=humidity,proto3" json:"humidity,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{4}
}

func (x *State) GetLightOn() LighStates {
	if x != nil {
		return x.LightOn
	}
	return LighStates_On
}

func (x *State) GetDoorLock() DoorLockStates {
	if x != nil {
		return x.DoorLock
	}
	return DoorLockStates_Open
}

func (x *State) GetChannel_1() ChannelStates {
	if x != nil {
		return x.Channel_1
	}
	return ChannelStates_ChannelOn
}

func (x *State) GetChannel_2() ChannelStates {
	if x != nil {
		return x.Channel_2
	}
	return ChannelStates_ChannelOn
}

func (x *State) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *State) GetPressure() float32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *State) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

type Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip      string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac     string `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	BleName string `protobuf:"bytes,3,opt,name=ble_name,json=bleName,proto3" json:"ble_name,omitempty"`
	Token   string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Info) Reset() {
	*x = Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{5}
}

func (x *Info) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Info) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Info) GetBleName() string {
	if x != nil {
		return x.BleName
	}
	return ""
}

func (x *Info) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ClientMessage_GetInfo
	//	*ClientMessage_SetState
	//	*ClientMessage_GetState
	Message isClientMessage_Message `protobuf_oneof:"message"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{6}
}

func (m *ClientMessage) GetMessage() isClientMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ClientMessage) GetGetInfo() *GetInfo {
	if x, ok := x.GetMessage().(*ClientMessage_GetInfo); ok {
		return x.GetInfo
	}
	return nil
}

func (x *ClientMessage) GetSetState() *SetState {
	if x, ok := x.GetMessage().(*ClientMessage_SetState); ok {
		return x.SetState
	}
	return nil
}

func (x *ClientMessage) GetGetState() *GetState {
	if x, ok := x.GetMessage().(*ClientMessage_GetState); ok {
		return x.GetState
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_GetInfo struct {
	GetInfo *GetInfo `protobuf:"bytes,1,opt,name=get_info,json=getInfo,proto3,oneof"`
}

type ClientMessage_SetState struct {
	SetState *SetState `protobuf:"bytes,2,opt,name=set_state,json=setState,proto3,oneof"`
}

type ClientMessage_GetState struct {
	GetState *GetState `protobuf:"bytes,3,opt,name=get_state,json=getState,proto3,oneof"`
}

func (*ClientMessage_GetInfo) isClientMessage_Message() {}

func (*ClientMessage_SetState) isClientMessage_Message() {}

func (*ClientMessage_GetState) isClientMessage_Message() {}

type ControllerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*ControllerResponse_Info
	//	*ControllerResponse_State
	//	*ControllerResponse_Status
	Response isControllerResponse_Response `protobuf_oneof:"response"`
}

func (x *ControllerResponse) Reset() {
	*x = ControllerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerResponse) ProtoMessage() {}

func (x *ControllerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerResponse.ProtoReflect.Descriptor instead.
func (*ControllerResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{7}
}

func (m *ControllerResponse) GetResponse() isControllerResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ControllerResponse) GetInfo() *Info {
	if x, ok := x.GetResponse().(*ControllerResponse_Info); ok {
		return x.Info
	}
	return nil
}

func (x *ControllerResponse) GetState() *State {
	if x, ok := x.GetResponse().(*ControllerResponse_State); ok {
		return x.State
	}
	return nil
}

func (x *ControllerResponse) GetStatus() Statuses {
	if x, ok := x.GetResponse().(*ControllerResponse_Status); ok {
		return x.Status
	}
	return Statuses_Ok
}

type isControllerResponse_Response interface {
	isControllerResponse_Response()
}

type ControllerResponse_Info struct {
	Info *Info `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type ControllerResponse_State struct {
	State *State `protobuf:"bytes,2,opt,name=state,proto3,oneof"`
}

type ControllerResponse_Status struct {
	Status Statuses `protobuf:"varint,3,opt,name=status,proto3,enum=api.Statuses,oneof"`
}

func (*ControllerResponse_Info) isControllerResponse_Response() {}

func (*ControllerResponse_State) isControllerResponse_Response() {}

func (*ControllerResponse_Status) isControllerResponse_Response() {}

var File_proto_proto_proto protoreflect.FileDescriptor

var file_proto_proto_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x27, 0x0a, 0x0f, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x0a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x09, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2d, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0xa1, 0x02, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x2a, 0x0a, 0x08, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x67, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x07, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4f, 0x6e, 0x12, 0x30, 0x0a,
	0x09, 0x64, 0x6f, 0x6f, 0x72, 0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x6f, 0x72, 0x4c, 0x6f, 0x63, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x08, 0x64, 0x6f, 0x6f, 0x72, 0x4c, 0x6f, 0x63, 0x6b, 0x12,
	0x2f, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x31, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x31,
	0x12, 0x2f, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x32, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x32, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x22, 0x59, 0x0a, 0x04, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xa1, 0x01, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x07, 0x67, 0x65, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x09, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x2c, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x08, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x12, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x65, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42,
	0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x1d, 0x0a, 0x08, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x2a, 0x1d, 0x0a, 0x0a, 0x4c, 0x69,
	0x67, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6e, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x4f, 0x66, 0x66, 0x10, 0x01, 0x2a, 0x25, 0x0a, 0x0e, 0x44, 0x6f, 0x6f,
	0x72, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4f,
	0x70, 0x65, 0x6e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x01,
	0x2a, 0x2e, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4f, 0x6e, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4f, 0x66, 0x66, 0x10, 0x01,
	0x2a, 0x8a, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x4c,
	0x69, 0x67, 0x68, 0x74, 0x4f, 0x6e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x69, 0x67, 0x68,
	0x74, 0x4f, 0x66, 0x66, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x6f, 0x6f, 0x72, 0x4c, 0x6f,
	0x63, 0x6b, 0x4f, 0x70, 0x65, 0x6e, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x6f, 0x6f, 0x72,
	0x4c, 0x6f, 0x63, 0x6b, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x31, 0x4f, 0x6e, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x31, 0x4f, 0x66, 0x66, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x32, 0x4f, 0x6e, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x32, 0x4f, 0x66, 0x66, 0x10, 0x07, 0x42, 0x38, 0x5a,
	0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x73, 0x61, 0x6d,
	0x61, 0x72, 0x6f, 0x6d, 0x61, 0x6e, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x76, 0x5f, 0x68, 0x61, 0x63, 0x6b, 0x61, 0x74, 0x68, 0x6f, 0x6e, 0x2f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_proto_proto_rawDescOnce sync.Once
	file_proto_proto_proto_rawDescData = file_proto_proto_proto_rawDesc
)

func file_proto_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_proto_proto_rawDescData)
	})
	return file_proto_proto_proto_rawDescData
}

var file_proto_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_proto_proto_goTypes = []any{
	(Statuses)(0),              // 0: api.Statuses
	(LighStates)(0),            // 1: api.LighStates
	(DoorLockStates)(0),        // 2: api.DoorLockStates
	(ChannelStates)(0),         // 3: api.ChannelStates
	(States)(0),                // 4: api.States
	(*IdentifyRequest)(nil),    // 5: api.IdentifyRequest
	(*GetState)(nil),           // 6: api.GetState
	(*GetInfo)(nil),            // 7: api.GetInfo
	(*SetState)(nil),           // 8: api.SetState
	(*State)(nil),              // 9: api.State
	(*Info)(nil),               // 10: api.Info
	(*ClientMessage)(nil),      // 11: api.ClientMessage
	(*ControllerResponse)(nil), // 12: api.ControllerResponse
}
var file_proto_proto_proto_depIdxs = []int32{
	4,  // 0: api.SetState.state:type_name -> api.States
	1,  // 1: api.State.light_on:type_name -> api.LighStates
	2,  // 2: api.State.door_lock:type_name -> api.DoorLockStates
	3,  // 3: api.State.channel_1:type_name -> api.ChannelStates
	3,  // 4: api.State.channel_2:type_name -> api.ChannelStates
	7,  // 5: api.ClientMessage.get_info:type_name -> api.GetInfo
	8,  // 6: api.ClientMessage.set_state:type_name -> api.SetState
	6,  // 7: api.ClientMessage.get_state:type_name -> api.GetState
	10, // 8: api.ControllerResponse.info:type_name -> api.Info
	9,  // 9: api.ControllerResponse.state:type_name -> api.State
	0,  // 10: api.ControllerResponse.status:type_name -> api.Statuses
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_proto_proto_init() }
func file_proto_proto_proto_init() {
	if File_proto_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_proto_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IdentifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SetState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ControllerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_proto_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientMessage_GetInfo)(nil),
		(*ClientMessage_SetState)(nil),
		(*ClientMessage_GetState)(nil),
	}
	file_proto_proto_proto_msgTypes[7].OneofWrappers = []any{
		(*ControllerResponse_Info)(nil),
		(*ControllerResponse_State)(nil),
		(*ControllerResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_proto_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_proto_depIdxs,
		EnumInfos:         file_proto_proto_proto_enumTypes,
		MessageInfos:      file_proto_proto_proto_msgTypes,
	}.Build()
	File_proto_proto_proto = out.File
	file_proto_proto_proto_rawDesc = nil
	file_proto_proto_proto_goTypes = nil
	file_proto_proto_proto_depIdxs = nil
}
